### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [dimmus/eflete#11]
https://hosted.weblate.org/projects/eflete/eflete/#information
says GPLv3
whereas
https://github.com/dimmus/eflete/blob/master/COPYING
says LGPLv3

Can be changed in
https://hosted.weblate.org/settings/eflete/eflete/
and
https://hosted.weblate.org/settings/eflete/glossary/

**Comment by dimmus** [comment]
Thanks. Updated
