### ISSUE TITLE
Build fails on Ubuntu 23.10 (Mantic Minotaur)

### ISSUE THREAD

**Issue by batden** [dimmus/eflete#38]
Hello dimmus,

Just to let you know, Eflete fails to build on the upcoming Ubuntu mantic.
Everything's okay with the actual Ubuntu LTS though.

Full log here: https://pastebin.ubuntu.com/p/rVW6DfgXZF/

**Comment by dimmus** [comment]
@batden, i get it. Thanks.
Tryied on Ubuntu 23.04—have no problems. Test on Ubuntu 23.10 is on the way.

**Comment by dimmus** [comment]
Solved in 9b79f5a47fb5e88d291191fe73a46dbdb44a59c4
