### ISSUE TITLE
Meson build system

### ISSUE THREAD

**Issue by dimmus** [dimmus/eflete#7]
Not sure, but it might be worth switching to meson build system.
Eflete is not a huge package, so the compilation speed is not extremely critical issue.

Personally, i like good old autotools.

**Comment by dimmus** [comment]
Made some initial commits in separate [meson](https://github.com/dimmus/eflete/tree/meson) branch.

**Comment by dimmus** [comment]
Have a huge passion to try the [acr](https://github.com/radareorg/acr) as well.

> ACR tries to replace autoconf functionality generating a full-compatible 'configure' script (runtime flags). But using shell-script instead of m4. This means that ACR is faster, smaller and easy to use.

**Comment by eli-schwartz** [comment]
From a quick look at your meson branch I think it can be simplified a lot. At least the following:
- autotools defined a lot of config.h `PACKAGE_*` defines by default, but you do not actually use them so just don't bother? All you need basically is PACKAGE_NAME alone.
- `eflete_cargs = '-fvisibility=hidden'` and checking if the compiler supports it is not necessary, you can use Meson's `gnu_symbol_visibility: 'hidden'` kwarg and Meson will handle this for you
- in all cases where you use `== true`, you're checking if a function that returns a boolean, is equal to boolean true. `if true == true` then evaluates and returns the value `true`, and `if true` runs the code inside that block; you can just use `if func('thing')` e.g. `if cc.has_argument(cf)`
- cc.has_argument in a loop can be simplified to `cc.get_supported_arguments()` which returns a list of the supported ones. `eflete_cflags = cc.get_supported_arguments(eflete_cflags_try)`
- source files for a target do not *have* to include the header files, Meson figures this out anyway. autotools doesn't really need this information either, except that dist breaks if you don't include it
- `c_args: [..., '-I' + join_paths(meson.source_root(), 'src/bin/alloc'), ...]` should just be `include_directories: [..., 'src/bin/alloc', ...]`, you can avoid specifying the current source directory

**Comment by dimmus** [comment]
Eli, thanks. Highly informative. Certainly, i take a look.

You leveled up my meson skills :)

**Comment by eli-schwartz** [comment]
No problem :) I'm happy to give a more thorough review as that branch progresses, feel free to ping me.

**Comment by dimmus** [comment]
Fully switched to meson build system. Done!
Time to think about `meson wrap` support.
